### ISSUE TITLE
Fast Downward no longer supports Python 2.7 - breaks planning

### ISSUE THREAD

**Issue by nik7273** [zi-w/Kitchen2D#1]
I've been able to get Kitchen2D running fine for everything except planning (`plan_example.py`), because Fast Downward is now dependent on Python >= 3.6 as of December 2019: http://issues.fast-downward.org/issue939

They cited that Python 2.7 has reached the end of its lifecycle (as of Jan. 1, 2020). 

Specifically: 
``` Error: Translator only supports Python >= 3.6. ```

I will see if I have the time to port this repository to Python 3.6 (I'm in the middle of adapting Kitchen2D for another project), but for now wanted to let you know about this - thanks.

**Comment by caelan** [comment]
I also have an older fork of FastDownward (https://github.com/caelan/FastDownward) that still works with Python 2.7
